# Generated by Django 5.2.15 on 2026-07-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('not_started', 'Not Started')], default='not_started', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
