# Generated by Django 5.2.15 on 2026-07-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null for SuperAdmin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'company')},
        ),
    ]
