# Generated by Django 5.2.15 on 2026-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_address_company_logo_alter_company_subdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invitation',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
