# Generated by Django 6.0.7 on 2026-07-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0001_initial'),
        ('checklists', '0003 alter checklist status alter subtask status '),
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='linked_category',
            field=models.ForeignKey(blank=True, help_text='The Category (Tower) this template applies to, from Category Management.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='categorymanagement.category'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='linked_sub_category',
            field=models.ForeignKey(blank=True, help_text='The Sub Category (Floor) this template applies to, from Category Management.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='categorymanagement.subcategory'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='projects.project'),
        ),
    ]
