# Generated by Django 5.2.15 on 2026-07-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hurdle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('material_delay', 'Material Delay'), ('labour_shortage', 'Labour Shortage'), ('vendor_delay', 'Vendor Delay'), ('approval_pending', 'Approval Pending'), ('design_change', 'Design Change'), ('equipment_failure', 'Equipment Failure'), ('weather_delay', 'Weather Delay')], max_length=32)),
                ('affected_tower', models.CharField(blank=True, max_length=255)),
                ('responsible_department', models.CharField(choices=[('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Finishing', 'Finishing'), ('MEP', 'MEP'), ('Fire Safety', 'Fire Safety'), ('Structural', 'Structural'), ('Legal', 'Legal'), ('Admin', 'Admin')], max_length=32)),
                ('impact_days', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=16)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('affected_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hurdles', to='tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hurdles', to='projects.project')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
