# Generated by Django 5.2.15 on 2026-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurdles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hurdle',
            name='responsible_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hurdle',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
