# Generated by Django 5.2.15 on 2026-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=32),
        ),
    ]
