# Generated by Django 5.2.15 on 2026-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hierarchy_mode',
            field=models.CharField(choices=[('full', 'Full Hierarchy (Tower → Floor → Unit → Task)'), ('direct_task', 'Direct to Task')], default='full', max_length=20),
        ),
    ]
