# Generated by Django 5.2.17 on 2026-10-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_project_documentextraction'),
        ('projects', '0008_alter_project_company_alter_project_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_projects', to='documents.document'),
        ),
    ]
