from django.contrib.auth import get_user_model
from rest_framework import serializers

from checklists.models import ChecklistTemplate
from projects.models import Floor, Project, Tower, Unit

from .models import Task, TaskChatMessage, TaskChecklistItem, TaskComment

User = get_user_model()


class TaskChecklistItemSerializer(serializers.ModelSerializer):
    class Meta:
        model = TaskChecklistItem
        fields = ["id", "title", "completed"]


class TaskCommentSerializer(serializers.ModelSerializer):
    """Outputs {id, user, text, date} where `user` is a display name (see
    Tasks.tsx TaskDetailDialog.addComment)."""

    user = serializers.SerializerMethodField()

    class Meta:
        model = TaskComment
        fields = ["id", "user", "text", "date"]

    def get_user(self, obj):
        return obj.author.name if obj.author else "Unknown"


class TaskChatMessageSerializer(serializers.ModelSerializer):
    """Outputs {id, user, userId, text, createdAt} matching ApiChatMessage
    in lib/api.ts. `user` is a display name; `userId` is the raw FK id."""

    user = serializers.SerializerMethodField()
    user_id = serializers.IntegerField(source="author_id", read_only=True)

    class Meta:
        model = TaskChatMessage
        fields = ["id", "user", "user_id", "text", "created_at"]

    def get_user(self, obj):
        return obj.author.name if obj.author else "Unknown"


class TaskSerializer(serializers.ModelSerializer):
    """
    IMPORTANT: every explicitly-declared field below is named in snake_case
    (e.g. `project_id`, `delay_days`), never camelCase (`projectId`,
    `delayDays`) -- even though the JSON the frontend sends/receives IS
    camelCase.

    That translation is handled entirely by djangorestframework-camel-case's
    parser/renderer, which convert JSON keys to/from snake_case at the HTTP
    boundary. The parser runs BEFORE serializer validation, so by the time
    this serializer sees incoming data, "projectId" has already become
    "project_id" -- a field manually declared as `projectId` would never
    match it and would be (silently) treated as missing on every write.
    Fields we don't declare here at all (title, department, status, ...) are
    auto-generated by ModelSerializer from the model and are unaffected,
    since a single-word attribute name has nothing to convert.
    """

    # Renames from the model's bare FK attribute names ("project", "tower", ...)
    # to the "<relation>_id" pattern the frontend expects ("projectId", ...).
    project_id = serializers.PrimaryKeyRelatedField(source="project", queryset=Project.objects.all())
    tower_id = serializers.PrimaryKeyRelatedField(
        source="tower", queryset=Tower.objects.all(), required=False, allow_null=True
    )
    floor_id = serializers.PrimaryKeyRelatedField(
        source="floor", queryset=Floor.objects.all(), required=False, allow_null=True
    )
    unit_id = serializers.PrimaryKeyRelatedField(
        source="unit", queryset=Unit.objects.all(), required=False, allow_null=True
    )

    # ------------------------------------------------------------------
    # Single-owner assignment and single-predecessor dependency, to back
    # the "Assigned To" / "Depends On" selects added in TaskRelationsPanel
    # (Tasks.tsx). These are deliberately separate from the model's
    # existing `assigned_users` (M2M, multiple people) and `dependencies`
    # (M2M, multiple predecessors) -- the frontend only exposes a single
    # value for each right now. If you'd rather reuse the existing M2M
    # `dependencies` field for the "Depends On" dropdown instead of adding
    # a new `depends_on` FK, delete `depends_on` below and the frontend
    # should send/read `dependencies: [id]` (a one-item list) instead of a
    # scalar `dependsOn`.
    # ------------------------------------------------------------------
    assigned_to = serializers.PrimaryKeyRelatedField(
        queryset=User.objects.all(), required=False, allow_null=True
    )
    depends_on = serializers.PrimaryKeyRelatedField(
        queryset=Task.objects.all(), required=False, allow_null=True
    )
    parent_id = serializers.PrimaryKeyRelatedField(
        source="parent", queryset=Task.objects.all(), required=False, allow_null=True
    )
    subtasks = serializers.SerializerMethodField()

    # Renamed from "checklist_items" (the model's related_name) to the
    # shorter "checklist", matching the frontend's Task.checklist field.
    checklist = TaskChecklistItemSerializer(source="checklist_items", many=True, read_only=True)
    comments = TaskCommentSerializer(many=True, read_only=True)

    # Write-only convenience field so task creation can attach a checklist
    # template in one call, mirroring NewTaskDialog.tsx. Renamed from
    # "checklist_template" (the source attribute) to make its purpose clear.
    checklist_template_id = serializers.PrimaryKeyRelatedField(
        source="checklist_template", queryset=ChecklistTemplate.objects.all(), write_only=True, required=False
    )

    # ------------------------------------------------------------------
    # Read-only organization/company/entity display fields, mirroring the
    # organization_name/company_name/entity_name fields on ProjectSerializer.
    # Task has no organization/company/entity FK of its own -- these are
    # derived through task.project, exactly like the org-scoping in
    # get_queryset() does. SerializerMethodField (rather than
    # source="project.organization.name") so a project with no entity, or a
    # task with no project loaded yet, can't raise instead of returning null.
    # ------------------------------------------------------------------
    organization_id = serializers.SerializerMethodField()
    organization_name = serializers.SerializerMethodField()
    company_id = serializers.SerializerMethodField()
    company_name = serializers.SerializerMethodField()
    entity_id = serializers.SerializerMethodField()
    entity_name = serializers.SerializerMethodField()

    class Meta:
        model = Task
        fields = [
            "id", "title", "description", "department", "assigned_hod", "assigned_users",
            "assigned_to", "depends_on", "parent_id", "subtasks", "is_repetitive", "repeat_frequency", "is_self_task",
            "start_date", "end_date", "actual_start_date", "actual_end_date",
            "priority", "status", "dependencies", "checklist", "progress",
            "delay_days", "delay_reason", "critical_path",
            "project_id", "tower_id", "floor_id", "unit_id", "phase", "comments",
            "checklist_template_id",
            "organization_id", "organization_name", "company_id", "company_name",
            "entity_id", "entity_name",
            "created_at", "updated_at",
        ]
        # assigned_hod, assigned_users, dependencies, is_repetitive,
        # repeat_frequency, is_self_task, start_date, end_date,
        # actual_start_date, actual_end_date, delay_days, delay_reason and
        # critical_path are all auto-generated by ModelSerializer (no
        # explicit declaration needed) because their outer field name already
        # equals the model attribute name -- camelCase conversion of
        # "delay_days" -> "delayDays" (and "is_repetitive" -> "isRepetitive",
        # "repeat_frequency" -> "repeatFrequency", "is_self_task" ->
        # "isSelfTask") happens automatically, and required/allow_null are
        # correctly inferred from the model's null/blank/default.
        #
        # The one exception is "assigned_hod": camelCase conversion of
        # "assigned_hod" mechanically produces "assignedHod" (capital H,
        # lowercase "od"), not "assignedHOD". We standardize on "assignedHod"
        # everywhere (backend and frontend) rather than special-casing this
        # one acronym, since any manual override here would reintroduce the
        # exact bug this docstring describes.
        #
        # organization_id/organization_name/company_id/company_name/
        # entity_id/entity_name are new: read-only, derived from
        # task.project (see the get_* methods below), mirroring the same
        # fields on ProjectSerializer.

    def get_organization_id(self, obj):
        return obj.project.organization_id if obj.project else None

    def get_organization_name(self, obj):
        return obj.project.organization.name if obj.project and obj.project.organization else None

    def get_company_id(self, obj):
        return obj.project.company_id if obj.project else None

    def get_company_name(self, obj):
        return obj.project.company.company_name if obj.project and obj.project.company else None

    def get_entity_id(self, obj):
        return obj.project.entity_id if obj.project else None

    def get_entity_name(self, obj):
        return obj.project.entity.entity_name if obj.project and obj.project.entity else None

    def get_subtasks(self, obj):
        return [
            {
                "id": s.id,
                "title": s.title,
                "status": s.status,
                "progress": s.progress,
                "priority": s.priority,
                "assigned_to": s.assigned_to_id,
                "start_date": str(s.start_date) if s.start_date else None,
                "end_date": str(s.end_date) if s.end_date else None,
                "created_at": s.created_at.isoformat() if s.created_at else None,
            }
            for s in obj.subtasks.all()
        ]

    def validate(self, attrs):
        # A repeat frequency only makes sense when the task is actually
        # marked repetitive. Mirrors the frontend, which only shows the
        # frequency Select once "Repetitive task" is checked, and clears
        # repeat_frequency to null when it's unchecked.
        is_repetitive = attrs.get("is_repetitive", getattr(self.instance, "is_repetitive", False))
        if not is_repetitive:
            attrs["repeat_frequency"] = None

        # Guard against a task listing itself as its own dependency.
        depends_on = attrs.get("depends_on")
        if depends_on is not None and self.instance is not None and depends_on.pk == self.instance.pk:
            raise serializers.ValidationError({"depends_on": "A task cannot depend on itself."})

        # ------------------------------------------------------------------
        # ✅ Hierarchy enforcement, keyed entirely off the task's project —
        # project.hierarchy_mode is the single source of truth, there is no
        # hardcoded branch anywhere else in this codebase. Falls back to the
        # existing instance's project/tower/floor/unit on PATCH so a partial
        # update (e.g. just dragging a Kanban card) re-checks against the
        # *current* values rather than None.
        # ------------------------------------------------------------------
        project = attrs.get("project") or getattr(self.instance, "project", None)
        if project is not None:
            tower = attrs.get("tower", getattr(self.instance, "tower", None) if self.instance else None)
            floor = attrs.get("floor", getattr(self.instance, "floor", None) if self.instance else None)
            unit = attrs.get("unit", getattr(self.instance, "unit", None) if self.instance else None)

            if project.hierarchy_mode == project.HIERARCHY_DIRECT_TASK:
                # Silently drop tower/floor/unit rather than erroring, so a
                # stale client that still sends them doesn't block task
                # creation -- direct-mode tasks simply never attach to them.
                attrs["tower"] = None
                attrs["floor"] = None
                attrs["unit"] = None
            elif project.hierarchy_mode == project.HIERARCHY_FULL:
                # Tower, floor, and unit are optional when creating or editing tasks.
                pass

        return attrs

    def create(self, validated_data):
        template = validated_data.pop("checklist_template", None)
        assigned_users = validated_data.pop("assigned_users", [])
        dependencies = validated_data.pop("dependencies", [])
        task = Task.objects.create(**validated_data)
        if assigned_users:
            task.assigned_users.set(assigned_users)
        if dependencies:
            task.dependencies.set(dependencies)
        if template:
            TaskChecklistItem.objects.bulk_create(
                [
                    TaskChecklistItem(task=task, title=item.text, order=item.order)
                    for item in template.items.all()
                ]
            )
        return task

    def update(self, instance, validated_data):
        validated_data.pop("checklist_template", None)  # only used on create
        assigned_users = validated_data.pop("assigned_users", None)
        dependencies = validated_data.pop("dependencies", None)
        instance = super().update(instance, validated_data)
        if assigned_users is not None:
            instance.assigned_users.set(assigned_users)
        if dependencies is not None:
            instance.dependencies.set(dependencies)
        return instance


class TaskListSerializer(TaskSerializer):
    """Lightweight variant for list views: drops nested checklist/comments."""

    class Meta(TaskSerializer.Meta):
        fields = [f for f in TaskSerializer.Meta.fields if f not in ("checklist", "comments")]