# Generated by Django 5.2.17 on 2026-10-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_project_documentextraction'),
        ('tasks', '0005_alter_task_department_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='baseline_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='baseline_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_days',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_tasks', to='documents.document'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='source_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wbs_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=4)),
                ('lag_days', models.FloatField(default=0.0, help_text='Lag (+days) or lead (-days)')),
                ('source_expression', models.CharField(blank=True, help_text='e.g. 2FS+3d', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(help_text='The preceding task', on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='tasks.task')),
                ('task', models.ForeignKey(help_text='The dependent task (successor)', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='tasks.task')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('task', 'predecessor')},
            },
        ),
    ]
