# Generated by Django 5.2.17 on 2026-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_baseline_end_date_task_baseline_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='wbs_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
