# Generated by Django 5.2.15 on 2026-07-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_formation', 'In Formation'), ('registered', 'Registered'), ('committee_formed', 'Committee Formed')], default='in_formation', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societies', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='society.society')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
