# Generated by Django 5.2.15 on 2026-07-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('documents', '0002_document_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='compliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.complianceitem'),
        ),
    ]
