# Generated by Django 5.2.15 on 2026-07-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_compliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='task',
        ),
    ]
