# Generated by Django 5.2.15 on 2026-07-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_task'),
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='handover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='handover.handoverunit'),
        ),
    ]
