# Generated by Django 5.2.17 on 2026-10-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_handover'),
        ('projects', '0008_alter_project_company_alter_project_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('validated', 'Validated'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('doc_type', models.CharField(default='construction_schedule', max_length=64)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detected_project_name', models.CharField(blank=True, max_length=255)),
                ('detected_status_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.document')),
                ('imported_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
