# Generated by Django 5.2.15 on 2026-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('role', models.CharField(max_length=64)),
                ('days', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
