# Generated by Django 5.2.15 on 2026-07-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('tower', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('snagging', 'Snagging'), ('inspection', 'Inspection'), ('not_ready', 'Not Ready'), ('handed_over', 'Handed Over')], default='not_ready', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('buyer', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_units', to='projects.project')),
                ('unit_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_records', to='projects.unit')),
            ],
        ),
    ]
